### PR TITLE
removed jQuery dependency for primary functions

### PR DESCRIPTION
**Pull request by m4cky**
hi i'm more of a fronted-guy and new with Kirby so please bear with me if i'm making dumb mistakes :)

So i rewrote the Toggle and Flip function with native javascript… until you set "enhancedJS" to true you don't need any jQuery. 

Additional I played around with pushing the body down:
- I do that by reading the current margin-top value and then adding/subtracting.
- If you set the panelbar to show the body will be pushed down on DOM ready.
- The animation is currently linear (not good) and feels wonky but that can be improved.
- And if you choose to set the bar to bottom it will not interfere with your body tag at all.

the code is not fully production ready but maybe you can already give feedback?

### CODE REVIEW

**Comment by distantnative** [comment]
Love the attempt to remove more jquery-dependency!! thanks! will def include that for the switch/flip buttons.

Not sure on the margin-top magix for reasons discussed here: https://github.com/distantnative/panel-bar/issues/15
Also it seems as if the margin is added twice on top. But mainly I don't like that it also gets added when I already scrolled to the middle of the page and hence the current scroll position / content moves on flipping the panel bar.

**Comment by jenstornell** [comment]
Agree. If possible to remove jQuery dependence in a beautiful way with not much code, do it.

I would stay away from messing with the body margin. Maybe a standalone plugin for it with only JS + CSS if even needed.

**Comment by jenstornell** [comment]
I'm not sure about the animation thing. Kirby is known to be bloat free and really fast to work with, closer to core than most CMS.

The same thing I like with the plugins. Fast and clever.

If an animation should even be there it needs to be really really fast and always work like expected. If it feels like it slows down the flow just for a microsecond, don't animate.

That's what I think at least.

**Comment by distantnative** [comment]
For the moment, I took the jQuery-free part (thanks a lot for this!) but will leave out the margin/animation-part due to the reasons mentioned.

**Pull request closed without merging**
